### ISSUE TITLE
Building on Palmetto: kmod, --enable-static

### ISSUE THREAD

**Issue by skachm** [open-power/op-build#101]
kmod throws an error while configuring that '--enable-static" is not supported.

>
$ op-build palmetto_defconfig && op-build
...
...
\>\>\> host-kmod 17 Configuring
...
...
checking whether to build static libraries... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
configure: error: --enable-static is not supported by kmod
make: *** [/home/clarity/op-build/output/build/host-kmod-17/.stamp_configured] Error 1
make: Leaving directory `/home/clarity/op-build/buildroot'
$

EDIT: Ubuntu 14.04 on a Tyan Palmetto, default configuration. Close if this is related to gcc-multilib or g++-multilib.

**Comment by williamspatrick** [comment]
Jeremy, any ideas?  I don't think this is related to multilib support.  Maybe an old version of kmod?

**Comment by skachm** [comment]
This seems to be a 14.04 problem, I upgraded our other Palmetto to 14.10 and it built.

**Comment by anoo1** [comment]
The README specifies that 14.04 is supported, so would make sense to provide a patch for 14.04 LE.

Workaround is to comment out line 12321 on file op-build/output/build/host-kmod-17/configure:

if test "x$enable_static" = "xyes"; then :
# as_fn_error $? "--enable-static is not supported by kmod" "$LINENO" 5
fi

**Comment by anoo1** [comment]
Opened issue https://github.com/open-power/op-build/issues/162 to follow-up since this one is closed.
