### ISSUE TITLE
P9 SBE build process places p9_10.p9n_10.sbe_seeprom.bin file at root of source directory.

### ISSUE THREAD

**Issue by rlippert** [open-power/op-build#1093]
After running a power9 build, an output file from the SBE build is accidentally placed at the root of the buildroot directory which shows up as an untracked added file in git:

```
p9_10.p9n_10.sbe_seeprom.bin
```

I think the offending code that creates this file is here: https://github.com/open-power/sbe/blob/master/src/import/tools/imageProcs/p9_ipl_build.C#L337

The source comment mentions this is a "debug" file so I don't think it is actually used as part of the build.

**Comment by dcrowell77** [comment]
@sgupta2m @pragupta

**Comment by Shakeebbk** [comment]
@pragupta @rjknight ipl build tool is creating this temporary file - p9_10.p9n_10.sbe_seeprom.bin, in addition to the actual customized output file. Do we need this file for something or can it be removed?

**Comment by pragupta** [comment]
I have pushed up code to fix this.  It is currently in the review process.

**Comment by pragupta** [comment]
fixed by the following commit: https://github.com/open-power/sbe/commit/a36220b33148ceb1cb8fe78b1082e2fb3c485858
