### ISSUE TITLE
missing make and unzip packages in readme

### ISSUE THREAD

**Issue by Anibagepalli** [open-power/op-build#11]
missing make and unzip on build instructions for ubuntu 14.04 instructions

Building on *64-bit* Ubuntu/Debian systems
==========================================
2. Install the packages necessary for the build:
> sudo apt-get install cscope ctags libz-dev libexpat-dev libc6-dev-i386 gcc g++ git bison flex gcc-multilib g++-multilib libxml-simple-perl libxml-sax-perl make unzip

**Comment by ChipDart** [comment]
I think this can be closed. I tried with a fresh ubuntu-14.04.2-server-amd64.iso install and the readme instructions worked.
