### ISSUE TITLE
MRW processing can be incorrect for MSBSWAP on two socket systems.

### ISSUE THREAD

**Issue by williamspatrick** [open-power/op-build#129]
Include Hostboot change Ib5656de1eb076b956315c31e957e66c17aa3bfc1 into op-build.

**Comment by ploetzma** [comment]
Patch is in a pull request under

https://github.com/open-power/op-build/pull/131

**Comment by williamspatrick** [comment]
Hostboot change is now I733f9c09837482469365b4de533f3560d049d0a6 for this problem.
