### ISSUE TITLE
VPD parser issue affecting double-drop configs (1.2 candidate)

### ISSUE THREAD

**Issue by bofferdn** [open-power/op-build#140]
Requesting commit for this issue:
https://github.com/open-power/tyan-openpower/issues/59

To be pulled in to v1.2
Already in hostboot @
https://github.com/open-power/hostboot/commit/b13486920ba90ada1975271a6dd3e61cd8b96a66
Commit = b13486920ba90ada1975271a6dd3e61cd8b96a66

**Comment by williamspatrick** [comment]
Present in master-next.  Closing.
