### ISSUE TITLE
ppc64_cpu in petitboot ?

### ISSUE THREAD

**Issue by agangidi53** [open-power/op-build#1430]
There might be good reason for this. But in Power8 or Power9 servers (barreleye) I can't seem to get ppc64_cpu (frequency or smt) to get out an meaningful output (looks different cores are different SMT states ).  
Can someone please explain the reason for this, in a bit of detail ?

**Comment by sammj** [comment]
Could you please post some examples of what you're seeing?
There's a new `v1.3.4` release for ppc64_cpu that could help here, we're in the process of updating to that now.

**Comment by agangidi53** [comment]
@sammj 
It would nice to know the frequency before we kexec into our public cloud image. This will help our deployment team to dynamically migrate images between different free machines 

/ # ppc64_cpu --frequency
min:	18446744073.710 GHz (cpu -1)
max:	0.000 GHz (cpu -1)
avg:	0.000 GHz

**Comment by sammj** [comment]
This upstream commit should fix that: https://github.com/ibm-power-utilities/powerpc-utils/commit/c25ae395db914f1137bb8a718277ea4b6f69136b
We'll pick it up when we update to the `v1.3.4` tag.

**Comment by sammj** [comment]
https://github.com/open-power/op-build/pull/1432

**Comment by stewart-ibm** [comment]
Merged in with https://github.com/open-power/op-build/pull/1432
