### ISSUE TITLE
ability to specify custom skiboot repository

### ISSUE THREAD

**Issue by ajdlinux** [open-power/op-build#1602]
It would be useful to be able to point the skiboot package at a custom repository rather than just being able to specify a version from the main open-power/skiboot repo.

**Comment by ajdlinux** [comment]
Hmm, I hadn't thought of that...

**Comment by stewart-ibm** [comment]
Yeah, this is what the `SKIBOOT_SITE` buildroot magic is for. As such, I'll close this issue.

**Comment by ajdlinux** [comment]
So today I ran into this again, and this time it occurs to me that `SKIBOOT_SITE` etc are completely undocumented, and even grepping through the repo it's unclear what I should be setting it to.
