### ISSUE TITLE
host-flex 2.6.4 fails to build

### ISSUE THREAD

**Issue by cyrilbur-ibm** [open-power/op-build#1619]
Before people start tearing their hair out: 
```make[3]: *** [Makefile:1696: stage1scan.c] Segmentation fault (core dumped)```

When building:
```
commit cbac09a858a7c8773605ab1a36bd1ad1a576fa65 (HEAD -> master, origin/master, origin/HEAD)
Merge: c980f52 00dd65f
Author: Stewart Smith <stewart@linux.vnet.ibm.com>
Date:   Wed Nov 8 14:23:08 2017 +1100

    Merge branch 'release' with op-build v1.20
```
On ARCH Linux (looks like the bug is exposed by newer compilers)

Reported here: https://github.com/westes/flex/issues/265
Fixed here: https://github.com/ruslo/hunter/pull/1119

**Comment by shenki** [comment]
Fixed in Buildroot as of c128c5f3c79b31d89256ffbc5c650ba613d3d52b. This was released as part of Buiildroot 2017.11, and is in op-build master as of ac78ef66b9e10b6fc2109600a5658fbb7de12e4e
