### ISSUE TITLE
mbox on bmc doesn't respond correctly to hostboot loader in the mpipl path

### ISSUE THREAD

**Issue by rajadas2** [open-power/op-build#1945]
The OPAL is up in the system runtime, here we have software hacks to crash opal, which will trigger S0/S1 interrupts on SBE while going down. Basis those interrupts SBE run the mpipl isteps (which is the same path as Phyp TI)

Mpipl Start Path Istep -

istepStartMpipl
p9_suspend_powman
p9_query_core_access_state
istepMpiplRstClrTpmBits
p9_sbe_check_quiesce
p9_l2_flush
p9_l3_flush
p9_sbe_sequence_drtm
Mpipl Continue path -

istepMpiplSetFunctionalState
mpipl_dump_reg
mpipl_query_quad_access_state
mpipl_hcd_core_stopclocks
mpipl_hcd_cache_stopclocks
p9_quad_power_off
After this SBE Runs the istep 4& 5 on the Master core, which will trigger the hostbootloader again to start the initial sequence of fetching data from Pnor via Mbox.

Here Mbox fails to réspond like it did in the first boot. May be because it doesn't know the host has gone down and came up again and asking the same questions which he has answered before. (this is as per design to keep bmc agnostic of the host state other than runtime/standby).

Need to see why mbox doesn't respond to initial messages from hostboot loader the second time.

**Comment by dcrowell77** [comment]
We've done zero work on mpipl support in a BMC environment.  There are major differences from the FSP flow.  This is not currently high on our priority list.

@sgupta2m might be able to help with the SBE specifics

**Comment by rajadas2** [comment]
@dcrowell77 true, but this is a bug in BMC's mbox utility, where if hostbootloader starts again (mpipl case), mbox doesn't respond the same way it does in the first IPL.
but if you reset the mbox via this command on BMC "/usr/sbin/mboxctl --reset", hostbootloader works fine. So may be we need not mix it with mpipl flow, but as a plane bug in the mbox flow.

**Comment by dcrowell77** [comment]
You should open the bug under the openbmc (or whatever platform you are on) project then, they don't always watch op-build.

**Comment by hegdevasant** [comment]
issue is sorted out.. Also this is wrong place to open BMC related issue.

Lets close this one.

-Vasant
