### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by nunojesus** [open-power/op-build#2082]
Hi,

I have read your work so I decided to creat a logo for you. I hope you like it and you want to use it. I can give you all the formats of the design free. If you want to make changes please specify.

The logo concept are the letters O and P mixed together.

Greetings

![oplogo-model](https://user-images.githubusercontent.com/34600369/39528353-c55dd8e2-4e1b-11e8-9599-cf2f77a3e89e.png)

**Comment by matthiasbeyer** [comment]
Beware: this user opened The exact same post on one of my repositories which is named "op". Might be a scam.

**Comment by nunojesus** [comment]
It´s not a scam dont worry, if you want the logo I will do it, if you dont want just say no and close this issue.

I contribute to many projects with logo designs,

greetings

**Comment by matthiasbeyer** [comment]
Yes, that's why I wondered. I didn't want to offend you if this is legit, so apologies in this case. I hope you understand that this is rather unusual to the normal github user who gets maybe PRs with code, but never any free logo contributions.

If everything is legit, this is really great!

**Comment by nunojesus** [comment]
You can see here 2 of my logo contributions, and you can see in the Readme file my name as logo designer:

https://github.com/nityanandagohain/SoundHaven
https://github.com/MarxSoul55/cats_vs_dogs

Greetings
Nuno

**Comment by stewart-ibm** [comment]
Thanks for the idea and art, but I think if we end up having a use for a logo, we'll end up going with something consistent with the OpenPOWER branding through the foundation.
