### ISSUE TITLE
openpower_mambo_defconfig build broken in master-next

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/op-build#210]
Building on ppc64el, Ubuntu Utopic, building maste-next:
9fc43d14af7d88475c83fea09d8df662448427bc was successful
60781382ce8e192e892d87b14904b913ca6df278 failed with:

>>> linux dc97a6e626eaf22c9bd4baec3954fa5501ce1c63 Downloading
Doing full clone
Cloning into bare repository 'linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63'...
>>> linux dc97a6e626eaf22c9bd4baec3954fa5501ce1c63 Extracting
gzip -d -c /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/dl/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63.tar.gz | tar --strip-components=1 -C /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63  -xf -
>>> linux dc97a6e626eaf22c9bd4baec3954fa5501ce1c63 Patching
for p in  ; do if echo $p | grep -q -E "^ftp://|^http://" ; then support/scripts/apply-patches.sh /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63 /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/dl `basename $p` ; elif test -d $p ; then support/scripts/apply-patches.sh /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63 $p linux-\*.patch ; else support/scripts/apply-patches.sh /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63 `dirname $p` `basename $p` ; fi done
>>> linux dc97a6e626eaf22c9bd4baec3954fa5501ce1c63 Configuring
/usr/bin/install -m 0644 "/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/openpower/configs/linux/skiroot_defconfig" /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/arch/powerpc/configs/buildroot_defconfig
PATH="/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/bin:/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/sbin:/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/usr/bin:/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games" /usr/bin/make -j1 HOSTCC="/usr/bin/gcc" HOSTCFLAGS="" ARCH=powerpc INSTALL_MOD_PATH=/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/target CROSS_COMPILE=" /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/usr/bin/powerpc64-buildroot-linux-gnu-" DEPMOD=/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/sbin/depmod -C /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63 buildroot_defconfig
make[1]: Entering directory '/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63'
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
#
# configuration written to .config
#
make[1]: Leaving directory '/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63'
rm /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/arch/powerpc/configs/buildroot_defconfig
/bin/sed -i -e "/\\<CONFIG_BLK_DEV_INITRD\\>/d" /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.config
echo "CONFIG_BLK_DEV_INITRD=y" >> /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.config
# As the kernel gets compiled before root filesystems are
# built, we create a fake cpio file. It'll be
# replaced later by the real cpio archive, and the kernel will be
# rebuilt using the linux26-rebuild-with-initramfs target.
touch /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/images/rootfs.cpio
/bin/sed -i -e "/\\<CONFIG_INITRAMFS_SOURCE\\>/d" /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.config
echo "CONFIG_INITRAMFS_SOURCE=\"/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/images/rootfs.cpio\"" >> /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.config
/bin/sed -i -e "/\\<CONFIG_INITRAMFS_ROOT_UID\\>/d" /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.config
echo "CONFIG_INITRAMFS_ROOT_UID=0" >> /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.config
/bin/sed -i -e "/\\<CONFIG_INITRAMFS_ROOT_GID\\>/d" /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.config
echo "CONFIG_INITRAMFS_ROOT_GID=0" >> /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.config
/bin/sed -i -e "/\\<CONFIG_DEVTMPFS\\>/d" /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.config
echo "CONFIG_DEVTMPFS=y" >> /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.config
/bin/sed -i -e "/\\<CONFIG_DEVTMPFS_MOUNT\\>/d" /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.config
echo "CONFIG_DEVTMPFS_MOUNT=y" >> /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.config
/bin/sed -i -e "/\\<CONFIG_INOTIFY_USER\\>/d" /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.config
echo "CONFIG_INOTIFY_USER=y" >> /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.config
yes '' | PATH="/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/bin:/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/sbin:/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/usr/bin:/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games" /usr/bin/make -j1 HOSTCC="/usr/bin/gcc" HOSTCFLAGS="" ARCH=powerpc INSTALL_MOD_PATH=/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/target CROSS_COMPILE=" /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/usr/bin/powerpc64-buildroot-linux-gnu-" DEPMOD=/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/sbin/depmod -C /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63 oldconfig
make[1]: Entering directory '/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63'
scripts/kconfig/conf --oldconfig Kconfig
#
# configuration written to .config
#
make[1]: Leaving directory '/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63'
yes: standard output: Broken pipe
yes: write error
>>> linux dc97a6e626eaf22c9bd4baec3954fa5501ce1c63 Building
PATH="/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/bin:/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/sbin:/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/usr/bin:/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games" /usr/bin/make -j41 HOSTCC="/usr/bin/gcc" HOSTCFLAGS="" ARCH=powerpc INSTALL_MOD_PATH=/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/target CROSS_COMPILE=" /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/usr/bin/powerpc64-buildroot-linux-gnu-" DEPMOD=/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/sbin/depmod -C /home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63 zImage.epapr
make[1]: Entering directory '/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63'
scripts/kconfig/conf --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  WRAP    arch/powerpc/include/generated/asm/clkdev.h
  WRAP    arch/powerpc/include/generated/asm/hash.h
  WRAP    arch/powerpc/include/generated/asm/irq_work.h
  CHK     include/generated/uapi/linux/version.h
  UPD     include/generated/uapi/linux/version.h
  UPD     include/config/kernel.release
  HOSTCC  scripts/basic/bin2c
  WRAP    arch/powerpc/include/generated/asm/mcs_spinlock.h
  CHK     include/generated/utsrelease.h
  UPD     include/generated/utsrelease.h
  WRAP    arch/powerpc/include/generated/asm/rwsem.h
  WRAP    arch/powerpc/include/generated/asm/preempt.h
  WRAP    arch/powerpc/include/generated/asm/scatterlist.h
  WRAP    arch/powerpc/include/generated/asm/vtime.h
  WRAP    arch/powerpc/include/generated/asm/trace_clock.h
  HOSTCC  scripts/pnmtologo
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/conmakehash
  CC      scripts/mod/empty.o
  SHIPPED scripts/dtc/dtc-parser.tab.h
  SHIPPED scripts/dtc/dtc-lexer.lex.c
  SHIPPED scripts/dtc/dtc-parser.tab.c
  HOSTCC  scripts/mod/mk_elfconfig
  HOSTCC  scripts/dtc/dtc.o
  HOSTCC  scripts/dtc/checks.o
  HOSTCC  scripts/dtc/data.o
  HOSTCC  scripts/dtc/fstree.o
  HOSTCC  scripts/dtc/flattree.o
  HOSTCC  scripts/dtc/util.o
  HOSTCC  scripts/dtc/livetree.o
  HOSTCC  scripts/dtc/treesource.o
  CC      scripts/mod/devicetable-offsets.s
  HOSTCC  scripts/dtc/srcpos.o
  HOSTCC  scripts/dtc/dtc-parser.tab.o
  GEN     scripts/mod/devicetable-offsets.h
  MKELF   scripts/mod/elfconfig.h
  HOSTCC  scripts/mod/file2alias.o
  HOSTCC  scripts/mod/sumversion.o
  HOSTCC  scripts/mod/modpost.o
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
  HOSTLD  scripts/dtc/dtc
  HOSTLD  scripts/mod/modpost
  CC      kernel/bounds.s
  GEN     include/generated/bounds.h
  CC      arch/powerpc/kernel/asm-offsets.s
  GEN     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  CC      init/main.o
  CHK     include/generated/compile.h
  CC      init/do_mounts.o
  CC      init/do_mounts_rd.o
  CC      init/do_mounts_initrd.o
  CC      init/do_mounts_md.o
  CC      init/initramfs.o
  CC      init/init_task.o
  HOSTCC  usr/gen_init_cpio
  CC      arch/powerpc/kernel/cputable.o
  CC      arch/powerpc/kernel/ptrace.o
  CC      arch/powerpc/kernel/syscalls.o
  CC      arch/powerpc/kernel/irq.o
  CC      arch/powerpc/kernel/align.o
  CC      arch/powerpc/kernel/signal_32.o
  CC      arch/powerpc/kernel/vdso.o
  CC      arch/powerpc/kernel/pmc.o
  CC      arch/powerpc/kernel/process.o
  CPP     arch/powerpc/kernel/systbl_chk.i
  CC      arch/powerpc/kernel/idle.o
  CC      arch/powerpc/kernel/signal.o
  CC      arch/powerpc/kernel/sysfs.o
  CC      arch/powerpc/kernel/prom.o
  CC      arch/powerpc/kernel/cacheinfo.o
  CC      arch/powerpc/mm/fault.o
  CC      arch/powerpc/kernel/traps.o
  CC      arch/powerpc/kernel/time.o
  CC      arch/powerpc/mm/mem.o
  CC      arch/powerpc/kernel/setup-common.o
  CC      arch/powerpc/kernel/udbg.o
  CC      arch/powerpc/mm/pgtable.o
  CC      arch/powerpc/mm/gup.o
  CC      arch/powerpc/kernel/io.o
  CC      arch/powerpc/mm/mmap.o
  AS      arch/powerpc/kernel/misc.o
  CC      arch/powerpc/mm/pgtable_64.o
  AS      arch/powerpc/kernel/misc_64.o
  CC      arch/powerpc/kernel/dma.o
  CC      arch/powerpc/mm/init_64.o
  AS      arch/powerpc/lib/string.o
  UPD     include/generated/compile.h
  CC      init/version.o
  GEN     usr/initramfs_data.cpio.gz
  LDS     arch/powerpc/kernel/vdso32/vdso32.lds
  AS      usr/initramfs_data.o
  CC      arch/powerpc/kernel/setup_64.o
  CC      arch/powerpc/mm/hash_utils_64.o
  VDSO32A arch/powerpc/kernel/vdso32/sigtramp.o
  LD      usr/built-in.o
/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/usr/bin/powerpc64-buildroot-linux-gnu-ld: unrecognised emulation mode: elf64lppc
Supported emulations: elf64ppc elf32ppclinux elf32ppc elf32ppcsim
  LDS     arch/powerpc/kernel/vdso64/vdso64.lds
scripts/Makefile.build:336: recipe for target 'usr/built-in.o' failed
make[2]: *** [usr/built-in.o] Error 1
Makefile:929: recipe for target 'usr' failed
make[1]: *** [usr] Error 2
make[1]: *** Waiting for unfinished jobs....
  AS      arch/powerpc/mm/slb_low.o
  CC      arch/powerpc/lib/alloc.o
  CC      arch/powerpc/mm/slb.o
  VDSO64A arch/powerpc/kernel/vdso64/sigtramp.o
  VDSO32A arch/powerpc/kernel/vdso32/gettimeofday.o
  AS      arch/powerpc/lib/crtsavres.o
  CC      arch/powerpc/lib/devres.o
  VDSO64A arch/powerpc/kernel/vdso64/gettimeofday.o
  AS      arch/powerpc/lib/copypage_64.o
  CC      arch/powerpc/mm/hash_native_64.o
  AS      arch/powerpc/mm/hash_low_64.o
  VDSO32A arch/powerpc/kernel/vdso32/datapage.o
  AS      arch/powerpc/lib/copyuser_64.o
  VDSO64A arch/powerpc/kernel/vdso64/datapage.o
  VDSO32A arch/powerpc/kernel/vdso32/cacheflush.o
  VDSO32A arch/powerpc/kernel/vdso32/note.o
  VDSO64A arch/powerpc/kernel/vdso64/cacheflush.o
  VDSO64A arch/powerpc/kernel/vdso64/note.o
  VDSO32A arch/powerpc/kernel/vdso32/getcpu.o
  CC      arch/powerpc/lib/usercopy_64.o
  AS      arch/powerpc/lib/mem_64.o
  CC      arch/powerpc/kernel/sys_ppc32.o
  CC      arch/powerpc/kernel/signal_64.o
  VDSO64A arch/powerpc/kernel/vdso64/getcpu.o
  CC      arch/powerpc/mm/tlb_hash64.o
  VDSO32L arch/powerpc/kernel/vdso32/vdso32.so.dbg
  CC      arch/powerpc/mm/mmu_context_hash64.o
  AS      arch/powerpc/lib/hweight_64.o
  AS      arch/powerpc/lib/copyuser_power7.o
/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/usr/lib/gcc/powerpc64-buildroot-linux-gnu/4.8.3/../../../../powerpc64-buildroot-linux-gnu/bin/ld: unrecognised emulation mode: elf32lppclinux
Supported emulations: elf64ppc elf32ppclinux elf32ppc elf32ppcsim
collect2: error: ld returned 1 exit status
arch/powerpc/kernel/vdso32/Makefile:33: recipe for target 'arch/powerpc/kernel/vdso32/vdso32.so.dbg' failed
make[3]: *** [arch/powerpc/kernel/vdso32/vdso32.so.dbg] Error 1
scripts/Makefile.build:404: recipe for target 'arch/powerpc/kernel/vdso32' failed
make[2]: *** [arch/powerpc/kernel/vdso32] Error 2
make[2]: *** Waiting for unfinished jobs....
  CC      arch/powerpc/mm/numa.o
  AS      arch/powerpc/lib/string_64.o
  VDSO64L arch/powerpc/kernel/vdso64/vdso64.so.dbg
  CC      arch/powerpc/mm/slice.o
/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/usr/lib/gcc/powerpc64-buildroot-linux-gnu/4.8.3/../../../../powerpc64-buildroot-linux-gnu/bin/ld: unrecognised emulation mode: elf64lppc
Supported emulations: elf64ppc elf32ppclinux elf32ppc elf32ppcsim
collect2: error: ld returned 1 exit status
arch/powerpc/kernel/vdso64/Makefile:26: recipe for target 'arch/powerpc/kernel/vdso64/vdso64.so.dbg' failed
make[3]: *** [arch/powerpc/kernel/vdso64/vdso64.so.dbg] Error 1
scripts/Makefile.build:404: recipe for target 'arch/powerpc/kernel/vdso64' failed
make[2]: *** [arch/powerpc/kernel/vdso64] Error 2
  CC      arch/powerpc/mm/hugetlbpage.o
  AS      arch/powerpc/lib/memcpy_power7.o
  AS      arch/powerpc/lib/copypage_power7.o
  AS      arch/powerpc/lib/memcpy_64.o
  CC      arch/powerpc/lib/sstep.o
  AS      arch/powerpc/lib/ldstfp.o
  CC      arch/powerpc/lib/locks.o
  CC      arch/powerpc/lib/vmx-helper.o
  CC      arch/powerpc/lib/code-patching.o
  CC      arch/powerpc/lib/feature-fixups.o
  CC      arch/powerpc/lib/xor_vmx.o
  LD      init/mounts.o
/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/usr/bin/powerpc64-buildroot-linux-gnu-ld: unrecognised emulation mode: elf64lppc
Supported emulations: elf64ppc elf32ppclinux elf32ppc elf32ppcsim
scripts/Makefile.build:390: recipe for target 'init/mounts.o' failed
make[2]: *** [init/mounts.o] Error 1
Makefile:929: recipe for target 'init' failed
make[1]: *** [init] Error 2
Makefile:929: recipe for target 'arch/powerpc/kernel' failed
make[1]: *** [arch/powerpc/kernel] Error 2
  LD      arch/powerpc/mm/built-in.o
/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/usr/bin/powerpc64-buildroot-linux-gnu-ld: unrecognised emulation mode: elf64lppc
Supported emulations: elf64ppc elf32ppclinux elf32ppc elf32ppcsim
scripts/Makefile.build:336: recipe for target 'arch/powerpc/mm/built-in.o' failed
make[2]: *** [arch/powerpc/mm/built-in.o] Error 1
Makefile:929: recipe for target 'arch/powerpc/mm' failed
make[1]: *** [arch/powerpc/mm] Error 2
  LD      arch/powerpc/lib/built-in.o
/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/host/usr/bin/powerpc64-buildroot-linux-gnu-ld: unrecognised emulation mode: elf64lppc
Supported emulations: elf64ppc elf32ppclinux elf32ppc elf32ppcsim
scripts/Makefile.build:336: recipe for target 'arch/powerpc/lib/built-in.o' failed
make[2]: *** [arch/powerpc/lib/built-in.o] Error 1
Makefile:929: recipe for target 'arch/powerpc/lib' failed
make[1]: *** [arch/powerpc/lib] Error 2
make[1]: Leaving directory '/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63'
package/pkg-generic.mk:177: recipe for target '/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.stamp_built' failed
make: *** [/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/output/build/linux-dc97a6e626eaf22c9bd4baec3954fa5501ce1c63/.stamp_built] Error 2
make: Leaving directory '/home/jenkins/workspace/op-build-master-next/defconfig/openpower_mambo/label_exp/utopic/buildroot'
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE

**Comment by williamspatrick** [comment]
Fixed with #213.
