### ISSUE TITLE
Add nvram and ppc64_cpu to default config

### ISSUE THREAD

**Issue by shenki** [open-power/op-build#233]
I think it would be useful to have the `powerpc-utils` tools in the Petitboot environment. Can we please add `nvram` and `ppc64_cpu`?

**Comment by sammj** [comment]
'nvram' which is included in powerpc-utils is especially useful since Petitboot uses it to save configuration options, such as autoboot settings. (Certainly I've heard "Why can't I disable autoboot!?" several times in the office.)
