### ISSUE TITLE
Latest Palmetto Builds fail to post

### ISSUE THREAD

**Issue by seanbruno** [open-power/op-build#2551]
I'm unsure where to start bisecting the builds in jenkins.  The last build I tried, after flashing, does not boot or post petitboot at all.  I have no debug information as the system emits no text over SOL.

I tried this build: https://openpower.xyz/job/openpower/job/openpower-op-build/label=slave,target=palmetto/1558/

**Comment by stewartsmith** [comment]
Since POWER8 and palmetto support was removed in 40f804058414ddf4518ac07866bb58af74db20a2, this can probably be closed now.
