### ISSUE TITLE
Use a non-linked /var/*, to enable chroot-style petitboot plugins

### ISSUE THREAD

**Issue by jk-ozlabs** [open-power/op-build#263]
We have some petitboot changes landing soon, which add a chroot-style plugin (for example, to add IO configuration tools from external vendors). This will depend on having `/var/*` as actual directories, instead of links in /tmp.

Filing this issue as a tracking item, patch coming soon.

**Comment by stewart-ibm** [comment]
merged as part of https://github.com/open-power/op-build/pull/274 - so looks like we can close this.
