### ISSUE TITLE
ppc64_cpu can not read correct CPU frequency in Petitboot shell

### ISSUE THREAD

**Issue by johnhihi** [open-power/op-build#298]
We use op-build latest release v1.7(https://github.com/open-power/op-build/commit/074727053356fd1ee42fce0f4ee4ea7580c12db3) to build palmetto pnor, and we found in petitboot shell can not read frequency correctly, but v1.6(https://github.com/open-power/op-build/commit/3f9d9b55365cc179da9f8565180e32a78bb2a150) works fine. Below shows the v1.7 running result.

/ # ppc64_cpu --frequency
min:    18446744073.710 GHz (cpu -1)
max:    0.000 GHz (cpu -1)
avg:    0.000 GHz

**Comment by stewart-ibm** [comment]
Fixed in 1b0f8d44211019010ae993b5736b88fbbe4fa2bd
