### ISSUE TITLE
Make ppe42 toolchain part of buildroot SDK

### ISSUE THREAD

**Issue by ghost** [open-power/op-build#2997]
Seeing as we have https://github.com/open-power/op-build/issues/799 and no prospect of someone getting the arch and  code into a state where it could be upstream, nor of hardware stopping inventing new architectures rather than reusing existing ones in a way that's simple, we could maybe instead work out how we can make the ppe42 toolchain part of the buildroot produced SDK and use that rather than rebuild it every time.

**Comment by dcrowell77** [comment]
FYI @dgilbert999

**Comment by klauskiwi** [comment]
I believe this was fixed with #3625
