### ISSUE TITLE
buildroot 2015.11.1

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/op-build#343]
--- a/CHANGES
+++ b/CHANGES
@@ -1,3 +1,13 @@
+2015.11.1, Released December 5th, 2015
+
+	Fix for issue with the host package RPATH check when a custom host
+	directory (BR2_HOST_DIR=/path/to/somewhere) is used.
+
+	Important (and/or security related) bugfixes for busybox,
+	dropbear, libpng and openssl.
+
+	Updated/fixed packages: busybox, dropbear, gawk, libpng, openssl
+

**Comment by shenki** [comment]
This was merged in https://github.com/open-power/op-build/commit/1f2f3fd3e1b4ba3e2997bae8ed3ac8854b845123
