### ISSUE TITLE
Build fails on Debian Buster ppc64el

### ISSUE THREAD

**Issue by madscientist159** [open-power/op-build#3634]
We use Debian Stretch ppc64el to build and develop our official firmware, but there is interest in moving to Debian Buster ppc64el for this task.  Unfortunately, the builds fail in the HCODE component on ppc64el, but succeed on amd64 according to a third party report.  Since we can't use amd64 due to both policy and practical reasons, this means we are stuck on the older Debian Stretch builders until this is resolved.

The failure on ppc64el is attached:

[hcode_build_extract.log](https://github.com/open-power/op-build/files/4651858/hcode_build_extract.log)

**Comment by klauskiwi** [comment]
You need this fix https://github.com/open-power/ppe42-gcc/pull/6

**Comment by klauskiwi** [comment]
I'll consider this as closed.. Feel free to reopen if there's still an issue..
