### ISSUE TITLE
Move to buildroot 2016.02

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/op-build#388]

**Comment by stewart-ibm** [comment]
I've mailed the list with requests to look at these trees:

https://github.com/stewart-ibm/buildroot/tree/2016.02-op-build
https://github.com/stewart-ibm/op-build/tree/buildroot-2016.02

**Comment by shenki** [comment]
Hey @stewart-ibm, looking good! I've got some additional commits in my branch here:

https://github.com/shenki/buildroot/commits/2016.02-op-build

The summary:
* busybox version bump: security updates
* powerpc-utils: version bump, this went into master yesterday so you hadn't seen it
* dropbear: version bump: security updates, systemd init so we drop @sammj's 'prevent install of init script' patch 

We need to ensure that dropbear does not start at boot. This could be achieved by setting `DROPBEAR_INSTALL_INIT_SYSTEMD`, but I assume this would stop us from being able to do `service start dropbear`. We could remove `/etc/systemd/system/multi-user.target.wants/dropbear.service` from the rootfs? Is there a better practice here?

**Comment by stewart-ibm** [comment]
Doesn't https://github.com/stewart-ibm/buildroot/commit/1951655fb0c45dab90a21829c77b8347df665e88 get rid of the dropbear install?

We can have a script that runs at the end of everything and cleans things up.... but we could also just add an option to install teh init script somewhere where it's disabled by default.

**Comment by stewart-ibm** [comment]
After an on-IRC hint from @shenki , I see we're talking newer dropbear that only has systemd activation...

we should likely just wipe out *all* systemd activation scripts as a final step of image generation.

**Comment by shenki** [comment]
Was this closed-fixed? Perhaps a we should link to the commit when closing bugs

**Comment by shenki** [comment]
Found it: https://github.com/open-power/op-build/compare/911dc99fa7...10be651e90

**Comment by stewart-ibm** [comment]
I'm still so *incredibly* used to Launchpad doing that auto-magically. At some point, around 2024, I'll probably lose that habit :)
