### ISSUE TITLE
mihawk_defconfig openpower-pnor aa4c350255616b6406830fd6b564aebefaf7add4

### ISSUE THREAD

**Issue by hamzy** [open-power/op-build#4069]
[root@mihawklp111 home]# git clone --recursive https://github.com/open-power/op-build.git
[root@mihawklp111 home]# cd op-build/
[root@mihawklp111 op-build]# export FORCE_UNSAFE_CONFIGURE=1
[root@mihawklp111 op-build]# ./op-build mihawk_defconfig && ./op-build
...
>>> openpower-pnor aa4c350255616b6406830fd6b564aebefaf7add4 Downloading
--2021-04-10 20:56:01--  https://github.com/open-power/pnor/archive/aa4c350255616b6406830fd6b564aebefaf7add4/openpower-pnor-aa4c350255616b6406830fd6b564aebefaf7add4.tar.gz
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/open-power/pnor/tar.gz/aa4c350255616b6406830fd6b564aebefaf7add4 [following]
--2021-04-10 20:56:02--  https://codeload.github.com/open-power/pnor/tar.gz/aa4c350255616b6406830fd6b564aebefaf7add4
Resolving codeload.github.com (codeload.github.com)... 140.82.114.10
Connecting to codeload.github.com (codeload.github.com)|140.82.114.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/home/op-build/output/build/.openpower-pnor-aa4c350255616b6406830fd6b564aebefaf7add4.tar.gz.hUUkU6/output’

/home/op-build/output/build/.openpower-pnor-aa4     [ <=>                                                                                                   ]  17.09K  --.-KB/s    in 0.01s   

2021-04-10 20:56:02 (1.36 MB/s) - ‘/home/op-build/output/build/.openpower-pnor-aa4c350255616b6406830fd6b564aebefaf7add4.tar.gz.hUUkU6/output’ saved [17498]

WARNING: no hash file for openpower-pnor-aa4c350255616b6406830fd6b564aebefaf7add4.tar.gz
>>> openpower-pnor aa4c350255616b6406830fd6b564aebefaf7add4 Extracting
gzip -d -c /home/op-build/dl/openpower-pnor/openpower-pnor-aa4c350255616b6406830fd6b564aebefaf7add4.tar.gz | /home/op-build/output/host/bin/tar --strip-components=1 -C /home/op-build/output/build/openpower-pnor-aa4c350255616b6406830fd6b564aebefaf7add4   -xf -
>>> openpower-pnor aa4c350255616b6406830fd6b564aebefaf7add4 Patching

Applying openpower-pnor-20200618-change-kernel-size-to-24MB.patch using patch: 
patching file p9Layouts/defaultPnorLayout_64.xml
Hunk #1 FAILED at 222.
Hunk #2 FAILED at 233.
Hunk #3 FAILED at 243.
Hunk #4 FAILED at 253.
Hunk #5 FAILED at 263.
Hunk #6 FAILED at 271.
Hunk #7 FAILED at 283.
Hunk #8 FAILED at 291.
Hunk #9 FAILED at 301.
Hunk #10 FAILED at 310.
Hunk #11 FAILED at 320.
Hunk #12 FAILED at 329.
Hunk #13 FAILED at 339.
Hunk #14 FAILED at 350.
Hunk #15 FAILED at 360.
Hunk #16 FAILED at 370.
Hunk #17 FAILED at 380.
Hunk #18 FAILED at 389.
18 out of 18 hunks FAILED -- saving rejects to file p9Layouts/defaultPnorLayout_64.xml.rej
make: *** [package/pkg-generic.mk:209: /home/op-build/output/build/openpower-pnor-aa4c350255616b6406830fd6b564aebefaf7add4/.stamp_patched] Error 1
make: Leaving directory '/home/op-build/buildroot'

**Comment by klauskiwi** [comment]
Hi Mark. The patch probably needs a refresh after some changes to the openpower-pnor p9layout file - I'll have a look today
