### ISSUE TITLE
op-build alias gone without README update

### ISSUE THREAD

**Issue by scprek** [open-power/op-build#408]
README indicates to do the following, which no longer works.

```bash
git clone --recursive git@github.com:open-power/op-build.git
cd op-build
. op-build-env
op-build palmetto_defconfig && op-build
```
Current error
```
> . op-build-env
-bash: op-build-env: line 11: syntax error near unexpected token `('
-bash: op-build-env: line 11: `op-build () {'
```

I know I can simply run "op-build" from the top directory now.

**Comment by williamspatrick** [comment]
What version of bash are you running?  There have been a few changes lately to that alias, which were suppose to make it more widely supported and not less. 

There is no intended change here that requires README to be updated. Let's figure out why the alias is no longer working for you. 

Patrick

**Comment by scprek** [comment]
Hoping this was just a nested shell issue. Austin pool machines are GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu). I was in an ssh session and did a pull to get the latest, then ran into this problem, but now after exiting and trying again it work.

```
smcprek@gfw160: /esw/san2/smcprek/open-power/forks/op-build
> . op-build-env 
-bash: op-build-env: line 11: syntax error near unexpected token `('
-bash: op-build-env: line 11: `op-build () {'

smcprek@gfw160: /esw/san2/smcprek/open-power/forks/op-build
> bash --version
GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

smcprek@gfw160: /esw/san2/smcprek/open-power/forks/op-build
> exit
logout
Connection to gfw160 closed.

smcprek@mac: ~
> ssh gfw160

smcprek@gfw160: /esw/san2/smcprek/open-power/forks/op-build
> bash --version
GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

smcprek@gfw160: /esw/san2/smcprek/open-power/forks/op-build
> . op-build-env 
```

**Comment by shenki** [comment]
I've done this before; the problem is caused by sourcing op-build-env twice in the one shell
