### ISSUE TITLE
Review kernel modules

### ISSUE THREAD

**Issue by shenki** [open-power/op-build#453]
In light of https://github.com/open-power/op-build/pull/452, we should check through the .config produced by our current build and ensure that only modules we require are enabled

**Comment by stewart-ibm** [comment]
i think we're right now on *modules* for the most part.

Although we do bring in a lot with default=y which we may not need, and indeed may not be tested much (at all?)

Ideas on what to do here?

**Comment by stewart-ibm** [comment]
I'll go and close this particular issue, but we should probably open a new one for going through what drivers we have =y that we get due to "default=y"
