### ISSUE TITLE
Move to buildroot 2016.05

### ISSUE THREAD

**Issue by shenki** [open-power/op-build#476]
WIP is at

  https://github.com/shenki/op-build/tree/buildroot-2016.05
  https://github.com/shenki/buildroot/tree/2016.05-op-build

This is based on Buildroot's 2016.05-rc1. It builds a working firmware that runs on a palmetto.

TODO:
 - update config options (fragments? https://github.com/open-power/op-build/issues/457)
 - try to upstream Stewart's fakeroot fix (they didn't take it: http://lists.busybox.net/pipermail/buildroot/2016-March/154911.html)

**Comment by stewart-ibm** [comment]
We may want to do the board defconfig cleanups in two passes, one rearranging things the other updating for new buildroot. my guess is that we haven't done a savedefconfig for a very long time.

**Comment by shenki** [comment]
Yes, they should be separate patches.

We are up to date wrt savedefconfig - whenever I update them I do a savedefconfig.

**Comment by stewart-ibm** [comment]
Solved by https://github.com/open-power/op-build/pull/504
