### ISSUE TITLE
Ensure MRW_ENHANCED_GROUPING_NO_MIRRORING attribute is correct for all systems.

### ISSUE THREAD

**Issue by williamspatrick** [open-power/op-build#493]
Hostboot commit open-power/hostboot@784d1b2e made a change to the meaning of the attribute MRW_ENHANCED_GROUPING_NO_MIRRORING.  The statement from the memory team is as follows:

> Users moving to mss_eff_grouping.C v1.37 or newer must default the machine readable workbook attribute ATTR_MRW_ENHANCED_GROUPING_NO_MIRRORING to FALSE for all system types.  Note a TRUE setting will prohibit the use of memory mirroring mode and MCS grouping of 4. Failure to properly set the attribute ATTR_MRW_ENHANCED_GROUPING_NO_MIRRORING may result in either degraded memory performance or boot failures.

**Comment by stewart-ibm** [comment]
Is this something we need for v1.10 ?

**Comment by williamspatrick** [comment]
Just waiting on Firestone.  I suspect that one is wrong.

**Comment by williamspatrick** [comment]
All set now!  Thanks.
