### ISSUE TITLE
Garrison platforms don't build locales

### ISSUE THREAD

**Issue by sammj** [open-power/op-build#534]
The garrison_defconfig only builds the "C" and "en_US" locales. Is there a reason Garrison doesn't build the full list like other platforms, or should I send a quick PR?

**Comment by williamspatrick** [comment]
I don't know of any reason.  @ploetzma , @wghoffa , @stewart-ibm , @austinwrx ?

**Comment by stewart-ibm** [comment]
It's quite conceivable that "someone forgot" or "copied from palmetto which doesn't have them for... reasons"... It likely *should* have them now though

**Comment by sammj** [comment]
Assuming no one comes in with a last minute reason against I've made a new PR: https://github.com/open-power/op-build/pull/535

**Comment by sammj** [comment]
Closing as https://github.com/open-power/op-build/pull/535 is merged
