### ISSUE TITLE
NVMe driver and kexec don't play nice

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/op-build#537]
With NVMe enabled in petitboot and an NVMe card in the machine, it can lead to host kernel panics after kexec.

We should consider disabling NVMe until someone fixes this bug.

Cc: @bjking1

**Comment by shenki** [comment]
We have fixed the kexec issue and verified that it works on hardware. Do we still need to make this change?

**Comment by stewart-ibm** [comment]
Wasn't that for mlx5 cards rather than NVMe?

**Comment by shenki** [comment]
You're right. Sorry, wrong bug

**Comment by stewart-ibm** [comment]
and I was on the wrong (internal) bug.

**Comment by stewart-ibm** [comment]
Merged into master-next, closing.
