### ISSUE TITLE
ipmitool 1.8.17

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/op-build#569]
For some reason, someone has decided that ipmitool 1.8.17 is now what's recommended for Garrison systems for out of band.

Considering people tend to expect ipmitool to work from the petitboot shell, we should update too.

**Comment by shenki** [comment]
A patch will need to be submitted upstream to move to 1.8.17

From there we will cherry-pick that patch into our buildroot tree.

**Comment by stewart-ibm** [comment]
No compelling reason has been brought  forward as to why we should not just use whatever is in buildroot.

**Comment by stewart-ibm** [comment]
and by "compelling reason" I mean "any reason at all"

**Comment by stewart-ibm** [comment]
Closing - we're just going to follow buildroot.
