### ISSUE TITLE
Use busybox i2c-tools

### ISSUE THREAD

**Issue by shenki** [open-power/op-build#610]
We currently include the i2c-tools package in skiroot. As of buildroot 2016.08 busybox contains implementations of the tools. We should check that they meet our requirements, and if so, move to them.

**Comment by stewart-ibm** [comment]
@sammj do we use i2c-tools for anything in petitboot?

**Comment by sammj** [comment]
After chatting to @jk-ozlabs it looks like this is in just as a debugging aid - most likely we can move to the busybox version without issue, or drop it all together.

**Comment by stewart-ibm** [comment]
I think busybox version would be fine. It's just for debugging after all (which did prove useful to me)
