### ISSUE TITLE
Witherspoon/P9 Mambo kernel needs updating

### ISSUE THREAD

**Issue by ploetzma** [open-power/op-build#611]
P8 variants are using 4.4.18 

BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE="4.4.18"

P9 mambo is using a custom tarball I believe?

BR2_LINUX_KERNEL_CUSTOM_TARBALL_LOCATION="https://cdn.kernel.org/pub/linux/kernel/v4.x/testing/linux-4.7-rc3.tar.xz"

Should witherspoon also use the custom tarball?

**Comment by stewart-ibm** [comment]
We should bump both of them up to latest 4.8 RC. Does that sound about right @mikey  ?

**Comment by mikey** [comment]
yeah, the latest v4.8 RC would be the best.  v4.8 has a lot more functionality in it.

**Comment by shenki** [comment]
Fixed in master-next with https://github.com/open-power/op-build/pull/625
