### ISSUE TITLE
about  hostboot trace log

### ISSUE THREAD

**Issue by cooktail** [open-power/op-build#633]
Hi ,
       When I unset CONSOLE_OUTPUT_TRACE,The hostboot  IPL log is pithily,But I cannot see any trace message.
       Can the hostboot design into SOL print pithily log,And I can check the detail trace message in other places?

**Comment by williamspatrick** [comment]
Issue moved to [open-power/hostboot #65](https://github.com/open-power/hostboot/issues/65) via [**ZenHub**](https://www.zenhub.com/)
