### ISSUE TITLE
After an HMI Malfunction alert NRE system failed to boot from primary side and boots from golden side.

### ISSUE THREAD

**Issue by pridhiviraj** [open-power/op-build#703]
Install a pnor image on habanero system which is build from op-build master next branch, And execute a HMI Malfunction alert from host OS. System failed to boot from primary side saying enough hardware is not available(Both processors and mem buf's)  in the system and boots from the golden side pnor.

01:53:35 [pexpect]#./putscom -c 00000000 1c013100 1000000000000000
01:53:35 ./putscom -c 00000000 1c013100 1000000000000000
01:53:35   3.82673|Ignoring boot flags, incorrect version 0x0
01:53:35   3.91722|ISTEP  6. 3
01:53:35   4.36792|ISTEP  6. 4
01:53:35   4.36871|ISTEP  6. 5
01:53:35   9.11880|HWAS|PRESENT> DIMM[03]=AAAA0000AAAA0000
01:53:35   9.11880|HWAS|PRESENT> Membuf[04]=CC00000000000000
01:53:35   9.11881|HWAS|PRESENT> Proc[05]=8000000000000000
01:53:35   9.24349|ISTEP  6. 6
01:53:35  10.30301|================================================
01:53:35  10.30302|Error reported by unknown (0xE500)
01:53:35  10.30302|  <none>
01:53:35  10.30302|  ModuleId   0x0b unknown
01:53:35  10.30302|  ReasonCode 0xe504 unknown
01:53:35  10.30303|  UserData1  unknown : 0x0005000000000103
01:53:35  10.30303|  UserData2  unknown : 0xe2da000000000000
01:53:35  10.30303|User Data Section 0, type UD
01:53:35  10.30303|  Subsection type 0x04
01:53:35  10.30304|  ComponentId errl (0x0100)
01:53:35  10.30304|User Data Section 1, type UD
01:53:35  10.30304|  Subsection type 0x06
01:53:35  10.30305|  ComponentId errl (0x0100)
01:53:35  10.30305|  CALLOUT
01:53:35  10.30305|  HW CALLOUT
01:53:35  10.30305|  Reporting CPU ID: 15
01:53:35  10.30306|  Called out entity:
01:53:35  10.30306|User Data Section 2, type UD
01:53:35  10.30306|  Subsection type 0x33
01:53:35  10.30307|  ComponentId unknown (0xe500)
01:53:35  10.30307|User Data Section 3, type UD
01:53:35  10.30307|  Subsection type 0x01
01:53:35  10.30308|  ComponentId unknown (0xe500)
01:53:35  10.30308|  STRING
01:53:35  10.30308|  
01:53:35  10.30308|User Data Section 4, type UD
01:53:35  10.30309|  Subsection type 0x15
01:53:35  10.30309|  ComponentId hb-trace (0x3100)
01:53:35  10.30309|User Data Section 5, type UD
01:53:35  10.30309|  Subsection type 0x01
01:53:35  10.30310|  ComponentId unknown (0xe500)
01:53:35  10.30310|  STRING
01:53:35  10.30310|  
01:53:35  10.30310|User Data Section 6, type UD
01:53:35  10.30311|  Subsection type 0x03
01:53:35  10.30311|  ComponentId errl (0x0100)
01:53:35  10.30311|User Data Section 7, type UD
01:53:35  10.30312|  Subsection type 0x01
01:53:35  10.30312|  ComponentId errl (0x0100)
01:53:35  10.30312|  STRING
01:53:35  10.30312|  Hostboot Build ID: 
01:53:35  10.30313|User Data Section 8, type UD
01:53:35  10.30313|  Subsection type 0x04
01:53:35  10.30313|  ComponentId errl (0x0100)
01:53:35  10.30314|================================================
01:53:35  19.45794|System Shutting Down To Perform Reconfiguration
01:53:35  19.45795|IPMI: Initiate power cycle
01:53:35  19.45883|Stopping istep dispatcher
01:53:35  29.25931|IPMI: shutdown complete
01:53:35 
01:53:35   3.81797|Ignoring boot flags, incorrect version 0x0
01:53:35   3.90368|ISTEP  6. 3
01:53:35   4.35336|ISTEP  6. 4
01:53:35   4.35443|ISTEP  6. 5
01:53:35   9.10055|HWAS|PRESENT> DIMM[03]=AAAA0000AAAA0000
01:53:35   9.10056|HWAS|PRESENT> Membuf[04]=CC00000000000000
01:53:35   9.10056|HWAS|PRESENT> Proc[05]=8000000000000000
01:53:35   9.22599|ISTEP  6. 6
01:53:35   9.52100|================================================
01:53:35   9.52100|Error reported by hwas (0x0C00)
01:53:35   9.53040|  checkMinimumHardware found no functional master processor on this node
01:53:35   9.53041|  ModuleId   0x03 MOD_CHECK_MIN_HW
01:53:35   9.53041|  ReasonCode 0x0c07 RC_SYSAVAIL_NO_PROCS_FUNC
01:53:35   9.53041|  UserData1  HUID of node : 0x0002000000000000
01:53:35   9.53042|  UserData2  number of present procs : 0x0000000100000000
01:53:35   9.53042|User Data Section 0, type UD
01:53:35   9.53042|  Subsection type 0x15
01:53:35   9.53042|  ComponentId hb-trace (0x3100)
01:53:35   9.53043|User Data Section 1, type UD
01:53:35   9.53043|  Subsection type 0x06
01:53:35   9.53043|  ComponentId errl (0x0100)
01:53:35   9.53044|  CALLOUT
01:53:35   9.53044|  PROCEDURE ERROR
01:53:35   9.53044|  Procedure: 1
01:53:35   9.53044|User Data Section 2, type UD
01:53:35   9.53044|  Subsection type 0x03
01:53:35   9.53045|  ComponentId errl (0x0100)
01:53:35   9.53045|User Data Section 3, type UD
01:53:35   9.53045|  Subsection type 0x01
01:53:35   9.53046|  ComponentId errl (0x0100)
01:53:35   9.53046|  STRING
01:53:35   9.53046|  Hostboot Build ID: 
01:53:35   9.53046|================================================
01:53:35  20.02798|================================================
01:53:35  20.02799|Error reported by hwas (0x0C00)
01:53:35  20.02799|  checkMinimumHardware found no functional dimm cards.
01:53:35  20.02799|  ModuleId   0x03 MOD_CHECK_MIN_HW
01:53:35  20.02799|  ReasonCode 0x0c06 RC_SYSAVAIL_NO_MEMORY_FUNC
01:53:35  20.02800|  UserData1  HUID of node : 0x0002000000000000
01:53:35  20.02800|  UserData2  number of present, non-functional dimms : 0x0000001000000000
01:53:35  20.02800|User Data Section 0, type UD
01:53:35  20.02801|  Subsection type 0x15
01:53:35  20.02801|  ComponentId hb-trace (0x3100)
01:53:35  20.02801|User Data Section 1, type UD
01:53:35  20.02801|  Subsection type 0x06
01:53:35  20.02802|  ComponentId errl (0x0100)
01:53:35  20.02802|  CALLOUT
01:53:35  20.02802|  PROCEDURE ERROR
01:53:35  20.02802|  Procedure: 1
01:53:35  20.02803|User Data Section 2, type UD
01:53:35  20.02803|  Subsection type 0x03
01:53:35  20.02803|  ComponentId errl (0x0100)
01:53:35  20.02803|User Data Section 3, type UD
01:53:35  20.02804|  Subsection type 0x01
01:53:35  20.02804|  ComponentId errl (0x0100)
01:53:35  20.02804|  STRING
01:53:35  20.02804|  Hostboot Build ID: 
01:53:35  20.02804|================================================
01:53:35  22.03679|================================================
01:53:35  22.03679|Error reported by hwas (0x0C00)
01:53:35  22.03680|  checkMinimumHardware found no functional membufs
01:53:35  22.03680|  ModuleId   0x03 MOD_CHECK_MIN_HW
01:53:35  22.03680|  ReasonCode 0x0c09 RC_SYSAVAIL_NO_MEMBUFS_FUNC
01:53:35  22.03680|  UserData1  HUID of node : 0x0002000000000000
01:53:35  22.03681|  UserData2  number of present nonfunctional membufs : 0x0000000400000000
01:53:35  22.03681|User Data Section 0, type UD
01:53:35  22.03681|  Subsection type 0x15
01:53:35  22.03681|  ComponentId hb-trace (0x3100)
01:53:35  22.03682|User Data Section 1, type UD
01:53:35  22.03682|  Subsection type 0x06
01:53:35  22.03682|  ComponentId errl (0x0100)
01:53:35  22.03682|  CALLOUT
01:53:35  22.03683|  PROCEDURE ERROR
01:53:35  22.03683|  Procedure: 1
01:53:35  22.03683|User Data Section 2, type UD
01:53:35  22.03683|  Subsection type 0x03
01:53:35  22.03684|  ComponentId errl (0x0100)
01:53:35  22.03684|User Data Section 3, type UD
01:53:35  22.03684|  Subsection type 0x01
01:53:35  22.03684|  ComponentId errl (0x0100)
01:53:35  22.03684|  STRING
01:53:35  22.03685|  Hostboot Build ID: 
01:53:35  22.03685|================================================
01:53:35  23.34383|System shutting down with error status 0xC04
01:53:35  23.34384|================================================
01:53:35  23.34385|Error reported by hwas (0x0C00)
01:53:35  23.34385|  Insufficient hardware to continue.
01:53:35  23.34385|  ModuleId   0x03 MOD_CHECK_MIN_HW
01:53:35  23.34386|  ReasonCode 0x0c04 RC_SYSAVAIL_INSUFFICIENT_HW
01:53:35  23.34386|  UserData1   : 0x0000000000000000
01:53:35  23.34386|  UserData2   : 0x0000000000000000
01:53:35  23.34387|User Data Section 0, type UD
01:53:35  23.34387|  Subsection type 0x15
01:53:35  23.34387|  ComponentId hb-trace (0x3100)
01:53:35  23.34388|User Data Section 1, type UD
01:53:35  23.34388|  Subsection type 0x06
01:53:35  23.34388|  ComponentId errl (0x0100)
01:53:35  23.34389|  CALLOUT
01:53:35  23.34389|  PROCEDURE ERROR
01:53:35  23.34389|  Procedure: 1
01:53:35  23.34389|User Data Section 2, type UD
01:53:35  23.34390|  Subsection type 0x01
01:53:35  23.34390|  ComponentId errl (0x0100)
01:53:35  23.34390|  STRING
01:53:35  23.34391|  host_gard
01:53:35  23.34391|User Data Section 3, type UD
01:53:35  23.34391|  Subsection type 0x03
01:53:35  23.34392|  ComponentId errl (0x0100)
01:53:35  23.34392|User Data Section 4, type UD
01:53:35  23.34392|  Subsection type 0x01
01:53:35  23.34393|  ComponentId errl (0x0100)
01:53:35  23.34393|  STRING
01:53:35  23.34393|  Hostboot Build ID: 
01:53:35  23.34394|================================================
01:53:35   3.86058|Ignoring boot flags, incorrect version 0x0
01:53:35   3.94578|ISTEP  6. 3
01:53:35   4.40440|ISTEP  6. 4
01:53:35   4.40500|ISTEP  6. 5
01:53:35  22.04656|HWAS|PRESENT> DIMM[03]=AAAA0000AAAA0000
01:53:35  22.04657|HWAS|PRESENT> Membuf[04]=CC00000000000000
01:53:35  22.04657|HWAS|PRESENT> Proc[05]=8000000000000000
01:53:35  22.17042|ISTEP  6. 6
01:53:35  22.34236|ISTEP  6. 7
01:53:35  25.33005|ISTEP  6. 8
01:53:35  25.36816|ISTEP  6. 9
01:53:35  29.57677|ISTEP  6.10
01:53:35  29.57737|ISTEP  6.11
01:53:35  29.59662|ISTEP  6.12
01:53:35  29.60663|ISTEP  6.13
01:53:35  29.60706|ISTEP  7. 1
01:53:35  29.68313|ISTEP  7. 2
01:53:35  29.79595|ISTEP  7. 3
01:53:35  29.81608|ISTEP  7. 4
01:53:35  29.85370|ISTEP  7. 5
01:53:35  30.04746|ISTEP  7. 6
01:53:35  30.07631|ISTEP  7. 7
01:53:35  30.07722|ISTEP  7. 8
01:53:35  30.14905|ISTEP  7. 9
01:53:35  30.15622|ISTEP  8. 1
01:53:35  30.29226|ISTEP  8. 2
01:53:35  30.29296|ISTEP  8. 3
01:53:35  30.30285|ISTEP  8. 4
01:53:35  30.30383|ISTEP  8. 5
01:53:35  30.30697|ISTEP  8. 6
01:53:35  30.94379|ISTEP  8. 7
01:53:35  30.94426|ISTEP  8. 8
01:53:35  30.95427|ISTEP  9. 1
01:53:35  31.30507|ISTEP  9. 2
01:53:35  31.73534|ISTEP 10. 1
01:53:35  31.81262|ISTEP 10. 2
01:53:35  32.60284|ISTEP 10. 3
01:53:35  32.60357|ISTEP 10. 4
01:53:35  32.60409|ISTEP 10. 5
01:53:35  32.60474|ISTEP 10. 6
01:53:35  32.71246|ISTEP 10. 7
01:53:35  32.71346|ISTEP 10. 8
01:53:35  32.71447|ISTEP 10. 9
01:53:35  32.82838|ISTEP 10.10
01:53:35  32.82914|ISTEP 10.11
01:53:35  32.82985|ISTEP 10.12
01:53:35  32.88745|ISTEP 10.13
01:53:35  32.88814|ISTEP 10.14
01:53:35  32.88859|ISTEP 11. 1
01:53:35  33.08635|ISTEP 11. 2
01:53:35  33.08705|ISTEP 11. 3
01:53:35  33.17327|ISTEP 11. 4
01:53:35  33.28715|ISTEP 11. 5
01:53:35  33.40898|ISTEP 11. 6
01:53:35  34.47162|ISTEP 11. 7
01:53:35  34.47248|ISTEP 11. 8
01:53:35  34.81599|ISTEP 11. 9
01:53:35  34.81697|ISTEP 11.10
01:53:35  34.89581|ISTEP 11.11
01:53:35  34.89677|ISTEP 11.12
01:53:35  34.99622|ISTEP 11.13
01:53:35  34.99723|ISTEP 12. 1
01:53:35  35.10054|ISTEP 12. 2
01:53:35  35.16735|ISTEP 12. 3
01:53:35  35.19647|ISTEP 12. 4
01:53:35  35.54753|ISTEP 12. 5
01:53:35  35.54824|ISTEP 13. 1
01:53:35  35.64433|ISTEP 13. 2
01:53:35  35.67348|ISTEP 13. 3
01:53:35  35.67432|ISTEP 13. 4
01:53:35  35.69382|ISTEP 13. 5
01:53:35  35.70000|ISTEP 13. 6
01:53:35  36.60753|ISTEP 13. 7
01:53:35  36.81036|ISTEP 13. 8
01:53:35  36.96793|ISTEP 13. 9
01:53:35  39.02783|ISTEP 13.10
01:53:35  39.05997|ISTEP 13.11
01:53:35  39.17309|ISTEP 13.12
01:53:35  39.17397|ISTEP 14. 1
01:53:35  39.20469|ISTEP 14. 2
01:53:35  39.21441|ISTEP 14. 3
01:53:35  85.15817|ISTEP 14. 4
01:53:35  85.20774|ISTEP 14. 5
01:53:35  85.23916|ISTEP 14. 6
01:53:35  85.24150|ISTEP 14. 7
01:53:35  85.34222|ISTEP 14. 8
01:53:35  85.34389|ISTEP 15. 1
01:53:35  85.74334|ISTEP 15. 2
01:53:35  85.75356|ISTEP 15. 3
01:53:35  85.82117|ISTEP 16. 1
01:53:35  86.87396|ISTEP 16. 2
01:53:35  87.10676|ISTEP 16. 3
01:53:35  87.15116|ISTEP 16. 4
01:53:35  87.12904|ISTEP 18.13
01:53:35  87.29138|ISTEP 18.14
01:53:35  87.28164|ISTEP 20. 1
01:53:35  87.91131|ISTEP 21. 1
01:53:35  93.26491|htmgt|User power limit has been set to 900W
01:53:35  93.76507|htmgt|OCCs are now running in ACTIVE state
01:53:35 103.30867|ISTEP 21. 2
01:53:35 103.30910|ISTEP 21. 3
01:53:35 [53137873775,5] SkiBoot skiboot-5.3.6 starting...
01:53:35 [53137877173,5] initial console log level: memory 7, driver 5
01:53:35 [53137880025,6] CPU: P8 generation processor(max 8 threads/core)
01:53:35 [53137882590,7] CPU: Boot CPU PIR is 0x0010 PVR is 0x004d0200
01:53:35 [53137885447,7] CPU: Initial max PIR set to 0x1fff
01:53:35 [53138294505,5] OPAL table: 0x300b5a40 .. 0x300b5f00, branch table: 0x30002000
01:53:35 [53138299438,5] FDT: Parsing fdt @0xff00000
01:53:35 [53140377494,3] DT: dt_attach_root failed, duplicate sensor@58
01:53:35 [53142389075,5] XSCOM: chip 0x0 at 0x3fc0000000000 [P8 DD2.0]
01:53:35 [53142398086,6] XSTOP: XSCOM addr = 0x2010c82, FIR bit = 31
01:53:35 [53142401495,6] MFSI 0:0: Initialized
01:53:35 [53142403578,6] MFSI 0:2: Initialized
01:53:35 [53142405671,6] MFSI 0:1: Initialized
01:53:35 [53142668400,5] LPC: Bus on chip 0, access via XSCOM, PCB_Addr=0xb0020
01:53:35 [53142762513,5] LPC: Default bus on chip 0
01:53:35 [53142880539,6] MEM: parsing reserved memory from node /ibm,hostboot/reserved-memory
01:53:35 [53142890377,7] HOMER: Init chip 0
01:53:35 [53142892873,7]   PBA BAR0 : 0x0000003ffd800000
01:53:35 [53142895561,7]   PBA MASK0: 0x0000000000300000
01:53:35 [53142898185,7]   HOMER Image at 0x3ffd800000 size 4MB
01:53:35 [53142901695,7]   PBA BAR2 : 0x4000003ffda00000
01:53:35 [53142904348,7]   PBA MASK2: 0x0000000000000000
01:53:35 [53142906818,7]   SLW Image at 0x3ffda00000 size 1MB
01:53:35 [53142910348,7]   PBA BAR3 : 0x0000003fff800000
01:53:35 [53142912897,7]   PBA MASK3: 0x0000000000700000
01:53:35 [53142915461,7]   OCC Common Area at 0x3fff800000 size 8MB
01:53:35 [53142926071,7] CPU idle state device tree init
01:53:35 [53142928999,4] SLW: HB-provided idle states property found
01:53:35 [53143056348,5] PLAT: Fixing up PSI BAR on chip 0 BAR=3fffe80000001
01:53:35 [53143085735,7] AST: PNOR LPC offset: 0x0c000000
01:53:35 [53143154768,5] PLAT: Using virtual UART
01:53:35 [53143441906,7] UART: Using LPC IRQ 4
01:53:35 [54196199321,5] PLAT: Detected Habanero platform
01:53:35 [54228321629,5] CENTAUR: Found centaur for chip 0x0 channel 0
01:53:35 [54282545850,5] CENTAUR:   FSI host: 0x0 cMFSI0 port 3
01:53:35 [54338713779,5] CENTAUR: Found centaur for chip 0x0 channel 1
01:53:35 [54372718687,5] CENTAUR:   FSI host: 0x0 cMFSI0 port 2
01:53:35 [54372801746,5] CENTAUR: Found centaur for chip 0x0 channel 4
01:53:35 [54400046708,5] CENTAUR:   FSI host: 0x0 cMFSI0 port 7
01:53:35 [54460584078,5] CENTAUR: Found centaur for chip 0x0 channel 5
01:53:35 [54502416741,5] CENTAUR:   FSI host: 0x0 cMFSI0 port 6
01:53:35 [54542088997,5] PSI[0x000]: Found PSI bridge [working=1, active=0]
01:53:35 [1000132638,5] BT: Interface initialized, IO 0x00e4
01:53:35 [1461599615,5] NVRAM: Size is 576 KB
01:53:35 [1691828150,5] CAPI: Preloading ucode 200ea
01:53:35 [1691913127,5] FLASH: Queueing preload of 2/200ea
01:53:35 [1692035909,5] FLASH: Queueing preload of 0/0
01:53:35 [1692064636,7] FFS: Partition map size: 0x1000
01:53:35 [1694426531,7] FLASH: CAPP partition has ECC
01:53:35 [1697120929,7] FLASH: flash subpartition eyecatcher CAPP
01:53:35 [1697123183,7] FLASH: flash found subpartition: 1 size: 36432 offset 4096
01:53:35 [1801773967,5] FLASH: Queueing preload of 1/0
01:53:35 [1801802895,7] FFS: Partition map size: 0x1000
01:53:35 [1804066099,7] FLASH: BOOTKERNEL partition doesn't have ECC
01:53:35 [1899531668,5] Chip 0 Found PBCQ0 at /xscom@3fc0000000000/pbcq@2012000
01:53:35 [1899773094,5] Chip 0 Found PBCQ1 at /xscom@3fc0000000000/pbcq@2012400
01:53:35 [1965594104,5] Chip 0 Found PBCQ2 at /xscom@3fc0000000000/pbcq@2012800
01:53:35 [1981244591,3] PHB#0000: Base location code not found !
01:53:35 [2104937775,3] PHB#0001: Base location code not found !
01:53:35 [2167961878,3] PHB#0002: Base location code not found !
01:53:35 [2231242849,5] PCI: Resetting PHBs...
01:53:35 [3869785793,5] PCI: Probing slots...
01:53:35 [5611575408,5] PHB#0000:00:00.0 [ROOT] 1014 03dc R:00 C:060400 B:01..01 SLOT=Slot3 
01:53:35 [5611840345,5] PHB#0000:01:00.0 [EP  ] 14e4 168e R:10 C:020000 (      ethernet) LOC_CODE=Slot3
01:53:35 [5646756442,5] PHB#0000:01:00.1 [EP  ] 14e4 168e R:10 C:020000 (      ethernet) LOC_CODE=Slot3
01:53:35 [5729061962,5] PHB#0001:00:00.0 [ROOT] 1014 03dc R:00 C:060400 B:01..11 SLOT=Backplane PLX 
01:53:35 [5759552061,5] PHB#0001:01:00.0 [SWUP] 10b5 8748 R:ca C:060400 B:02..11 LOC_CODE=Backplane PLX
01:53:35 [5790409864,5] PHB#0001:02:01.0 [SWDN] 10b5 8748 R:ca C:060400 B:03..07 SLOT=Network Mezz 
01:53:35 [5840522380,5] PHB#0001:02:08.0 [SWDN] 10b5 8748 R:ca C:060400 B:08..08 SLOT=Storage Mezz 
01:53:35 [5862259311,5] PHB#0001:08:00.0 [LGCY] 1b4b 9235 R:11 C:010601 (          sata) LOC_CODE=Storage Mezz
01:53:35 [5927943800,5] PHB#0001:02:09.0 [SWDN] 10b5 8748 R:ca C:060400 B:09..09 SLOT=Backplane USB 
01:53:35 [5956303117,5] PHB#0001:09:00.0 [EP  ] 104c 8241 R:02 C:0c0330 (      usb-xhci) LOC_CODE=Backplane USB
01:53:35 [6017325162,5] PHB#0001:02:0a.0 [SWDN] 10b5 8748 R:ca C:060400 B:0a..0b SLOT=Backplane BMC 
01:53:35 [6038492714,5] PHB#0001:0a:00.0 [ETOX] 1a03 1150 R:03 C:060400 B:0b..0b LOC_CODE=Backplane BMC
01:53:35 [6117788966,5] PHB#0001:0b:00.0 [PCID] 1a03 2000 R:30 C:030000 (           vga) LOC_CODE=Backplane BMC
01:53:35 [6133332031,5] PHB#0001:02:10.0 [SWDN] 10b5 8748 R:ca C:060400 B:0c..0c SLOT=Slot2 
01:53:35 [6184149242,5] PHB#0001:0c:00.0 [EP  ] 14e4 1657 R:01 C:020000 (      ethernet) LOC_CODE=Slot2
01:53:35 [6235716031,5] PHB#0001:0c:00.1 [EP  ] 14e4 1657 R:01 C:020000 (      ethernet) LOC_CODE=Slot2
01:53:35 [6312566385,5] PHB#0001:0c:00.2 [EP  ] 14e4 1657 R:01 C:020000 (      ethernet) LOC_CODE=Slot2
01:53:35 [6329206806,5] PHB#0001:0c:00.3 [EP  ] 14e4 1657 R:01 C:020000 (      ethernet) LOC_CODE=Slot2
01:53:35 [6399201204,5] PHB#0001:02:11.0 [SWDN] 10b5 8748 R:ca C:060400 B:0d..11 SLOT=Slot1 
01:53:35 [6414091743,5] PHB#0002:00:00.0 [ROOT] 1014 03dc R:00 C:060400 B:01..01 SLOT=Slot4 
01:53:35 [6440224591,5] PHB#0002:01:00.0 [EP  ] 9005 028d R:01 C:010400 (          raid) LOC_CODE=Slot4
01:53:35 [6506925407,5] Releasing unused memory:
01:53:35 [6507056175,5]     ibm,firmware-heap: 2482000/13631488 used
01:53:35 [6551606086,5]     ibm,firmware-allocs-memory@0: 12845568/273909022720 used
01:53:35 [6594254465,5] Reserved regions:
01:53:35 [6644477041,5]   0x003fff800000..003fffffffff : ibm,occ-common-area@3fff800000
01:53:35 [6691217573,5]   0x003ffd800000..003ffdbfffff : ibm,homer-image@3ffd800000
01:53:35 [6735272190,5]   0x003ffd700000..003ffd7fffff : ibm,hbrt-vpd-image@3ffd700000
01:53:35 [6778811519,5]   0x003ffd6e0000..003ffd6fffff : ibm,hbrt-target-image@3ffd6e0000
01:53:35 [6822239656,5]   0x003ffd460000..003ffd6dffff : ibm,hbrt-code-image@3ffd460000
01:53:35 [6860380647,5]   0x000031c00000..000031ddffff : ibm,firmware-stacks
01:53:35 [6875551447,5]   0x000031000000..000031bfffff : ibm,firmware-data
01:53:35 [6911257286,5]   0x000030300000..000030ffffff : ibm,firmware-heap
01:53:35 [6932536159,5]   0x000030000000..0000302fffff : ibm,firmware-code
01:53:35 [6972699212,5]   0x000039c00000..00003a8401ff : ibm,firmware-allocs-memory@0
01:53:35 [6988248975,5] IPMI: Resetting boot count on successful boot
01:53:35 [7010895449,5] INIT: Waiting for kernel...
01:53:35 [8279328042,3] FLASH: No ROOTFS partition
01:53:35 [8280289311,5] INIT: Kernel loaded, size: 15728640 bytes (0 = unknown preload)
01:53:35 [8283571455,5] INIT: 64-bit LE kernel discovered
01:53:35 [8314438865,5] INIT: 64-bit kernel entry at 0x20010000
01:53:35 [8330074692,5] OCC: All Chip Rdy after 0 ms
01:53:35 [8393527940,5] Free space in HEAP memory regions:
01:53:35 [8393634191,5] Region ibm,firmware-heap free: a23fd0
01:53:35 [8406728730,5] Region ibm,firmware-allocs-memory@0 free: 10cd70
01:53:35 [8430483415,5] Total free: 11734336
01:53:35 [8462502966,5] INIT: Starting kernel at 0x20010000, fdt at 0x3055f208 (size 0x15750)
01:53:35 
01:53:35 
zImage starting: loaded at 0x0000000020010000 (sp: 0x0000000020ec9ed8)
01:53:35 
Allocating 0x1575554 bytes for kernel ...
01:53:35 
gunzipping (0x0000000000000000 <- 0x000000002001d000:0x0000000020ec7459)...done 0x13f0300 bytes
01:53:35 
01:53:35 
Linux/PowerPC load: 
01:53:35 
Finalizing device tree... flat tree at 0x20ed6520
01:53:35 
 -> smp_release_cpus()
01:53:35 spinning_secondaries = 79
01:53:35  <- smp_release_cpus()
01:53:35  <- setup_system()
01:53:35 
01:53:35 (B)0[1;24r[m[?7h[?1h=[H[J[H[J Petitboot (v1.3.1-828e2bd)
[1B [0mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq

**Comment by dcrowell77** [comment]
@zane131 Please confirm callouts for injected error with Henderson/Mueller.  I suspect this is just working as designed.

**Comment by stewart-ibm** [comment]
Golden side never worked correctly as far as I could see, and there's practically going to be no updates to how it works on p8 ever.

I don't think it's worth keeping this bug open.
