### ISSUE TITLE
Witherspoon and Zaius not on GCC6

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/op-build#755]
Witherspoon needs to build with GCC6.

I've set this to 1.13, but I suspect that it won't be met. I could just enable it and force someone to pick up the pieces though...

**Comment by williamspatrick** [comment]
Are there details of what isn't working?

**Comment by williamspatrick** [comment]
It's not realistic to expect this to be fixed and make its way through the process in the next week.  They probably need instructions on how to enable GCC6 to test and an explanation of what is all broken.

**Comment by stewart-ibm** [comment]
To enable GCC6, like we did in https://github.com/open-power/op-build/commit/8b90e5b4c83b1c1d532f3c0cf23090907cd6606f the following needs to be added to witherspoon_defconfig:
```
BR2_GCC_VERSION_6_X=y
```

... and then you work out what doesn't build.
