### ISSUE TITLE
System is not booting after an ipmi reprovision.

### ISSUE THREAD

**Issue by pridhiviraj** [open-power/op-build#764]
System is in below firmware level:
 Product Name          : OpenPOWER Firmware
 Product Version       : open-power-habanero-f8ed50e
 Product Extra         : 	buildroot-211bd05
 Product Extra         : 	skiboot-5.4.0
 Product Extra         : 	hostboot-94aeacf
 Product Extra         : 	linux-4.4.30-openpower1-418c9ff
 Product Extra         : 	petitboot-v1.3.1-f126151
 Product Extra         : 	habanero-xml-5565b8f-580b6c4
 Product Extra         : 	occ-e6e194f
 Product Extra         : 	hostboot-binaries-56532f5
 Product Extra         : 	capp-uco

Booted the system to stable runtime.
Did the ipmi reprovision:
# ipmitool raw 0x3a 0x1d
 03
# ipmitool raw 0x3a 0x1d
 03
# ipmitool raw 0x3a 0x1d
 03
# [  392.078082792,5] IPMI: PNOR access released

# ipmitool raw 0x3a 0x1d
 00
# ipmitool raw 0x3a 0x1d
 00

After reprovision completed, did a reboot from host OS.
reboot

[-1;-1f[-1;-1fUbuntu 16.10[-1;-1f.  .  .  .[-1;-1fUbuntu 16.10[-1;-1f.  .  .  .[-1;-1fUbuntu 16.10[-1;-1f.  .  .  .[-1;-1fUbuntu 16.10[-1;-1f.  .  .  .[  370.707241] reboot: Restarting system
[  370.707241] reboot: Resta[  463.211373487,5] OPAL: Reboot request...
rting system
[-1;-1fUbuntu 16.10[-1;-1f.  .  .  .[-1;-1fUbuntu 16.10[-1;-1f.  .  .  .[-1;-1f

System failed to boot.

**Comment by stewart-ibm** [comment]
Realistically, there's not going to be any bugs fixed in the AMI BMC implementation on p8 systems, so I don't think it's worth keeping this bug open.
