### ISSUE TITLE
Hostboot and OCC P8/P9 split breaks VERSION

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/op-build#876]
no longer picks up patches as part of VERSION

**Comment by dcrowell77** [comment]
@ploetzma - Please look into this.

**Comment by stewart-ibm** [comment]
I have a fix. Basically, it's impossible to work out if p8Patches or p9Patches are being selected.

I think the correct way is to split it. Have a virtual 'hostboot' package with hostboot-p8 and hostboot-p9 providing it. Then, patches are discovered the normal way.

It also means we don't have funny if conditions around versions.

There's also *other* brokenness in the VERSION output that I have patches for (but haven't reported an issue yet).

If my build succeeds here, I'll post a pull request.
