### ISSUE TITLE
Large files in rootfs.

### ISSUE THREAD

**Issue by williamspatrick** [open-power/op-build#90]
/etc/eudev/hwdb has large text files that are suspected to be unused.
/usr/locale/locale-archive is quite large considering only English is supported.

Can these files be reduced or removed?

**Comment by jk-ozlabs** [comment]
@sammj is looking at the hwdb at present. We support 11 languages (including English), hence the size of the locale db.

**Comment by sammj** [comment]
During my work with fbterm I was running with hwdb generation disabled (for decent space savings); I didn't test thoroughly but I did not notice any differences in general use with the hwdb missing. Are we aware of any specific devices that we'll require the hwdb for?

**Comment by stewart-ibm** [comment]
So, we've attacked a few things over the years to address this, and we can't currently see any big ticket obvious items to go squash.

Idea is we close this specific issue and open a new one for any specific items we find in the future.
